#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# DIWASP documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.

import os
import sys

# Add parent directory to path for autodoc
sys.path.insert(0, os.path.abspath("../"))

# Import version from package
try:
    import diwasp

    version = diwasp.__version__
    release = diwasp.__version__
except ImportError:
    version = "0.1.0"
    release = "0.1.0"

# -- General configuration ------------------------------------------------

# Sphinx extension modules
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.coverage",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",  # For Google/NumPy style docstrings
    "myst_parser",  # For Markdown support
]

# Generate autosummary automatically
autosummary_generate = True

# Add any paths that contain templates here, relative to this directory
templates_path = ["_templates"]

# The suffix(es) of source filenames
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document
master_doc = "index"

# General information about the project
project = "DIWASP-Python"
copyright = "2024, DIWASP Contributors"
author = "DIWASP Contributors"

html_show_copyright = False
html_show_sphinx = False

# The language for content autogenerated by Sphinx
language = None

# List of patterns to ignore when looking for source files
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = "pydata_sphinx_theme"

html_theme_options = {
    "collapse_navigation": True,
    "show_nav_level": 4,
    "navbar_align": "content",
    "navbar_center": ["navbar-nav"],
    "secondary_sidebar_items": ["page-toc", "edit-this-page"],
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/metocean/diwasp-python",
            "icon": "fab fa-github",
            "type": "fontawesome",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/diwasp/",
            "icon": "fas fa-box",
            "type": "fontawesome",
        },
    ],
}

html_sidebars = {
    "**": ["globaltoc.html"],
}

# Add any paths that contain custom static files
html_static_path = ["_static"]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar. Uncomment and add logo file if available
# html_logo = "_static/diwasp_logo.png"

# The name of an image file to use as favicon
# html_favicon = "_static/diwasp_logo.png"

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder
htmlhelp_basename = "diwaspdoc"

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper')
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt')
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [(master_doc, "diwasp.tex", "DIWASP Documentation", author, "manual")]

# -- Options for manual page output ---------------------------------------

# One entry per manual page
man_pages = [(master_doc, "diwasp", "DIWASP Documentation", [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files
texinfo_documents = [
    (
        master_doc,
        "diwasp",
        "DIWASP Documentation",
        author,
        "diwasp",
        "DIrectional WAve SPectrum analysis for Python",
        "Miscellaneous",
    )
]

# -- Options for autodoc --------------------------------------------------

# Sort members by source order
autodoc_member_order = "bysource"

# Remove parentheses from functions cross-referenced
add_function_parentheses = False

# -- Options for Napoleon (Google/NumPy docstring support) ---------------

napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True
